In [2]:
import pandas as pd

opc = pd.read_csv('http://172.16.26.217:3000/bigquery_ethereum_contracts_merge2020.csv', dtype={'swc_label': object, 'opcode': object})

opc

,_id,address,opcode,swc_label
0,240000,0x8da4feb3dd3643943c614ca793e8f59baae50544,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
1,240001,0xe1521029d2591ba2a0f92b6e744a825f665f748b,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
2,240002,0xe378696ce7ad55cfacc40337f476faf8fba9aff2,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
3,240003,0x1872b33bb33e372d6f039a8b6af2e1be228bda23,PUSH1 PUSH1 MSTORE CALLDATASIZE ISZERO PUSH2 J...,0000000000100000000000000000000000000
4,240004,0x6ef34258c0c8ae7acc688311189dfc783ebb5bfa,ORIGIN PUSH20 EQ ISZERO ADDRESS JUMPI PUSH20 S...,0000000000000001000000000000000000000
...,...,...,...,...
253829,29967,0xa8ba70d5c2fae0b92d5ef8607bf7de09916c3027,PUSH1 PUSH1 MSTORE PUSH1 CALLDATALOAD PUSH29 S...,0000001000000000000000000000000000000
253830,29968,0x69677e5c602c2e495ec059dbda9f46413a192cc0,PUSH1 PUSH1 MSTORE CALLDATASIZE ISZERO PUSH2 J...,0000000000000000000000000000000000000
253831,29969,0xf82b842bd96282ed2c50a2e64c8de1a9d6862825,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
253832,29970,0x401071960e0201430b5a882ce47300b534bd78ff,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000100000000000000000000000000
253833,29971,0xd2fcbec53476bb0fb8e278461cbaf5a949758356,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000

## Drop Corrupted Rows

In [3]:
for index, row  in opc.iterrows():
    if not isinstance(row['opcode'], str):
        opc = opc.drop([index])

In [4]:
opc

,_id,address,opcode,swc_label
0,240000,0x8da4feb3dd3643943c614ca793e8f59baae50544,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
1,240001,0xe1521029d2591ba2a0f92b6e744a825f665f748b,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
2,240002,0xe378696ce7ad55cfacc40337f476faf8fba9aff2,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
3,240003,0x1872b33bb33e372d6f039a8b6af2e1be228bda23,PUSH1 PUSH1 MSTORE CALLDATASIZE ISZERO PUSH2 J...,0000000000100000000000000000000000000
4,240004,0x6ef34258c0c8ae7acc688311189dfc783ebb5bfa,ORIGIN PUSH20 EQ ISZERO ADDRESS JUMPI PUSH20 S...,0000000000000001000000000000000000000
...,...,...,...,...
253829,29967,0xa8ba70d5c2fae0b92d5ef8607bf7de09916c3027,PUSH1 PUSH1 MSTORE PUSH1 CALLDATALOAD PUSH29 S...,0000001000000000000000000000000000000
253830,29968,0x69677e5c602c2e495ec059dbda9f46413a192cc0,PUSH1 PUSH1 MSTORE CALLDATASIZE ISZERO PUSH2 J...,0000000000000000000000000000000000000
253831,29969,0xf82b842bd96282ed2c50a2e64c8de1a9d6862825,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000
253832,29970,0x401071960e0201430b5a882ce47300b534bd78ff,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000100000000000000000000000000
253833,29971,0xd2fcbec53476bb0fb8e278461cbaf5a949758356,PUSH1 PUSH1 MSTORE PUSH1 CALLDATASIZE LT PUSH2...,0000000000000000000000000000000000000

In [5]:
opc.to_csv('CDS_opcode_cv1.csv', index=False)